## Anthony Ung, Sean Jerzewski, Gideon Kipkorir

Do Not turn in your table with millions of rows. (Save it for the next step)  
Instead turn in a summary with the following totals (for the 365 day period)
* Number of customers
* Total sales
* Total items bought
* Top 10 selling items (with product name not just an SKU) with counts

* You may compute the summaries in a database system if you donâ€™t want to complicate your code

In [6]:
import sqlite3 as lite

grocery_db = None

class db():
    def __init__(self, con, cur):
        self.con = con
        self.cur = cur

    def execute(self, sql):
        queryset = self.cur.execute(sql)
        return queryset

def connect():
    global grocery_db 
    con = lite.connect('store.db')
    cur = con.cursor()
    grocery_db = db(con = con, cur = cur)

def task_1_get_num_customers():
    sql = """
    SELECT
        COUNT(DISTINCT customerNumber)
    FROM
        sales_transactions
    """

    queryset = grocery_db.execute(sql).fetchone()
    print(f"Task 1 - Number of customers in database\n\
            {queryset[0]} Customers in database\n\
            \n\
            ")

def task_2_get_total_sales():
    sql = """
        SELECT
            SUM(salesPrice)
        FROM
            sales_transactions
    """
    
    queryset = grocery_db.execute(sql).fetchone()
    print(f"Task 2 - Total sales in Year 2024\n\
            ${queryset[0]} total sales in 2024\n\
            \n\
            ")

def task_3_total_items_bought():
    sql = """
        SELECT
            COUNT(*)
        FROM
            sales_transactions
    """
    
    queryset = grocery_db.execute(sql).fetchone()
    print(f"Task 3 - Total Items bought in 2024\n\
            {queryset[0]} items bought\n\
            \n\
            ")

def task_4_total_items_bought():
    sql = """
        SELECT
            product_name,
            COUNT(*) as count
        FROM
            sales_transactions AS st
        JOIN
            products AS p ON st.sku = p.sku
        GROUP BY
            p.sku
        ORDER BY
            count DESC
        LIMIT 10
    """
    
    queryset = grocery_db.execute(sql).fetchall()
    print(f"Task 4 - Top 10 products in 2024")
    for product_name, count in queryset:
        print(f"\t    {product_name} - {count}")

connect()
task_1_get_num_customers()
task_2_get_total_sales()
task_3_total_items_bought()
task_4_total_items_bought()

Task 1 - Number of customers in database
            1135 Customers in database


Task 2 - Total sales in Year 2024
            $72477734.916 total sales in 2024


Task 3 - Total Items bought in 2024
            17584898 items bought


Task 4 - Top 10 products in 2024
	    2.00% Milk - 53336
	    1.00% Milk - 53301
	    Whole Milk Milk - 53284
	    2.00% Milk - 53276
	    1.00% Milk - 52958
	    Whole Milk Milk - 52858
	    Jam Grape - 21243
	    Squeeze Jelly Grape - 21227
	    Jam Strawberry - 21223
	    Jelly Grape - 20943